#!/bin/sh
gitDir=$(git rev-parse --show-toplevel)  # get root of git working tree
if type ctags > /dev/null; then
    # Run ctags on root directory of git repo (unless in dotfiles)
    gitRepo=$(basename $gitDir)
    if [ "$gitRepo" != "dotfiles" ] ; then
        ctags -R $gitDir  # add/update ctags in repo
        # mv tags .git/tags  # hide tags in git repo
        echo "Updated ctags in" $gitDir
    fi
fi
